name: Bug report
description: "Things aren't working right? Create a bug report to let us know!"
body:
  - type: markdown
    attributes:
      value: |-
        ## Important: If this is a game issue, check out [our Discord server](https://discord.gg/rHJ2uqdquK) and [our Wiki](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting) to get help instead!
        Examples for valid issues: "Heroic doesn't open", "This button is out of place", "Heroic closes unexpectedly", "Installs get interrupted"
  - type: dropdown
    id: issue_type
    attributes:
      label: Issue Type
      options:
        - Bug
        - Feature Request
    validations:
      required: true
  - type: textarea
    id: bug_description
    attributes:
      label: Describe the issue
      description: 'A clear and concise description of what the issue is.'
    validations:
      required: true
  - type: textarea
    id: heroic_log
    attributes:
      label: Add logs
      description: 'Open up the "Settings" tab -> "Log" tab -> "Copy log content to clipboard" and paste it into here'
      render: text
    validations:
      required: true
  - type: textarea
    id: to_reproduce
    attributes:
      label: Steps to reproduce
      description: 'Steps to reproduce this behavior'
      value: |-
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: 'A clear and concise description of what you expected to happen.'
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
  - type: markdown
    attributes:
      value: |-
        ## Latest stable version of Heroic is 2.8.0. Please, update Heroic before reporting a bug if you have an older version.
  - type: dropdown
    id: heroic_version
    attributes:
      label: Heroic Version
      options:
        - Latest Stable
        - Latest Beta
        - main branch from GitHub
    validations:
      required: true
  - type: textarea
    id: systeminfo
    attributes:
      label: System Information
      value: |-
        - OS [e. g. "Ubuntu"]:
    validations:
      required: true
  - type: textarea
    id: additional_info
    attributes:
      label: Additional information
      description: Add any other context about the issue here.
  - type: checkboxes
    id: confirm_info
    attributes:
      label: Confirm all required information has been provided
      options:
        - value: confirm
          label: I confirm that I have provided all required information and that this is not an issue with a game.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |-
        ## Warning
        If the issue does not meet the criteria outlined above, it will be closed without further investigation.
